version: '2.1'

services:

  catalog.api:
    image: eshop/catalog.api
    build:
      context: ./src/Services/Catalog/Catalog.API
      dockerfile: Dockerfile    
    restart: on-failure
    depends_on:
      - sql.data
      - rabbitmq
    ports:
      - "5101:80"



  sql.data:
    image: mcr.microsoft.com/mssql/server:2017-latest

  nosql.data:
    image: mongo

 
      
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
