version: '3.6'
services:
  ordering_test:
    build: 
      context: ./Ordering.API
      args:
        source: obj/Docker/empty
    image: "ordering_test:latest"
    container_name: ordering_test
    # command: sh -c "cd /usr/local/bin && ./sayhelloworld.sh"
    volumes:
        - .\Ordering.API:/app:rw
        - ..\..\..\..\images:/app/images:rw
        - .\Ordering.API:/src:rw
        - C:\Users\Murali.Balasubramani\.nuget\packages\:/root/.nuget/packages:ro
        - C:\Program Files\dotnet\sdk\NuGetFallbackFolder:/root/.nuget/fallbackpackages:ro
        - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
        - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
#     networks: 
#       - dockercompose4019110096250588909_default

# networks: 
#   dockercompose4019110096250588909_default:
#     external: true