version: '3.6'
services:
  catalog_test:
    build: 
      context: ./Catalog.API
      args:
        source: obj/Docker/empty
    image: "catalog_test:latest"
    container_name: catalog_test
    # command: sh -c "cd /usr/local/bin && ./sayhelloworld.sh"
    volumes:
        - .\Catalog.API:/app:rw
        - ..\..\..\..\images:/app/images:rw
        - .\Catalog.API:/src:rw
        - C:\Users\DELL\.nuget\packages\:/root/.nuget/packages:ro
        - C:\Program Files\dotnet\sdk\NuGetFallbackFolder:/root/.nuget/fallbackpackages:ro
        - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
        - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
#     networks: 
#       - dockercompose4019110096250588909_default

# networks: 
#   dockercompose4019110096250588909_default:
#     external: true